[workspace]
members = [
    "crates/unremark",
    "crates/unremark_server"
]
resolver = "2"

[workspace.dependencies]
unremark = { path = "crates/unremark" }
unremark_server = { path = "crates/unremark_server" }
